// 1. EVENT PROPOGATION vs EVENT BUBBLING

// 2. EVENT.TARGET VS THIS.TARGET VS EVENT.CURRENTTARGET

//3. EVENT CAPTURING OR TRICKLING 

//4. HOT TO STOP EVENT BUBBLING OR CAPTURING 

//5. EVENT DELEGATION
